name: talk2me_flutter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # UI & Animations
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  gap: ^3.0.1

  # Utilities
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  get_it: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
